#!/usr/bin/env python3
"""Validate the low-friction judge and operator experience."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def check(name: str, condition: bool, evidence: str) -> tuple[str, bool, str]:
    return name, condition, evidence


def main() -> int:
    rules = (ROOT / "autonomy-gate" / "rules.md").read_text(encoding="utf-8")
    start = (ROOT / "docs" / "START_HERE.md").read_text(encoding="utf-8")
    root_readme = (ROOT / "README.md").read_text(encoding="utf-8")
    modes = (ROOT / "docs" / "USER_MODES.md").read_text(encoding="utf-8")

    adapter_paths = [
        ROOT / "adapters" / "claude" / "claude-code-CLAUDE.md",
        ROOT / "adapters" / "openai" / "codex-AGENTS.md",
    ]
    adapter_text = "\n".join(path.read_text(encoding="utf-8") for path in adapter_paths)

    results = [
        check(
            "ADOPT-01",
            "## RULE-14 — Build Handoff Pack Generation" in rules,
            "RULE-14 makes build handoff pack output part of the product contract.",
        ),
        check(
            "ADOPT-02",
            "BUILD HANDOFF PACK" in rules and "exactly three" in rules.lower(),
            "Build Handoff Packs preserve the three-section response contract.",
        ),
        check(
            "ADOPT-03",
            "16 runtime files" in start and "operating-contract.md" in start,
            "Beginner setup uses the canonical 16-file manifest and operating contract.",
        ),
        check(
            "ADOPT-04",
            "Fill in each bracketed field" not in adapter_text,
            "Code-agent adapters are generated by the Gate, not manually filled by users.",
        ),
        check(
            "ADOPT-05",
            all((ROOT / path).is_file() for path in (
                "adapters/README.md",
                "autonomy-gate/reference/README.md",
                "autonomy-gate/reference/templates/README.md",
                "examples/README.md",
            )),
            "Ambiguous public folders contain navigation guidance.",
        ),
        check(
            "ADOPT-06",
            "## Judge Path" in root_readme and "## Product Depth" in root_readme,
            "Root README separates the fast evaluation path from optional depth.",
        ),
        check(
            "ADOPT-07",
            "Follow identity.md, rules.md, and operating-contract.md." in root_readme
            and "Follow identity.md, rules.md, and operating-contract.md." in start,
            "Primary setup entry points use one canonical instruction.",
        ),
        check(
            "ADOPT-08",
            all(command in modes for command in ("ASSESS", "RESOLVE EVIDENCE", "SELECT ARCHITECTURE", "APPROVE", "REVIEW BUILD")),
            "The first-use journey exposes five primary operator commands.",
        ),
        check(
            "ADOPT-09",
            "fill in the brackets" not in modes.lower() and "copy, fill" not in modes.lower(),
            "Primary operator guidance requires no template translation.",
        ),
        check(
            "ADOPT-10",
            all(field in rules for field in ("Current state", "What the Gate completed", "What is blocked", "Who acts next", "Exact next action")),
            "Every state-changing artifact has an explicit owner and next action.",
        ),
    ]

    failures = 0
    for test_id, passed, evidence in results:
        status = "PASS" if passed else "FAIL"
        failures += not passed
        print(f"{status:4} {test_id} {evidence}")

    print(f"{len(results) - failures}/{len(results)} passed")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
